title: Landing page
email:
description: Client Landing Page
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twit-name
instagram_username: IG-name
facebook_username: FB-name

# show blog post excerpt in blog post list
show_excerpts: true

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
sass:
  style: compact # possible values: nested expanded compact compressed

defaults:
- scope:
    path: "" # an empty string here means all files in the project
    type: "posts" # previously `post` in Jekyll 2.2.
  values:
    permalink: "/blog/:title"

collections:
  blog_authors:
    output: false

# specifies how many items should be displayed per page in the blog
paginate: 4
paginate_path: "/blog/page:num/"